#!/usr/bin/env python3
"""Full Maestro verification suite.

Order matters: sync provider adapters first, then validate provider config,
then run structural / metadata / dependency audits.

This is a real gate: it fails when a check is genuinely broken, not merely when
a file is absent. `scan_results.json` is intentionally regenerated last so it
reflects the actual state of this run.
"""

import json
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from common_utils import print_header, print_success, print_fail, print_info, print_warning

ROOT = Path(__file__).resolve().parent.parent


def run_script(script_name: str) -> bool:
    print_info(f"Running {script_name}...")
    result = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / script_name)],
        capture_output=True,
        text=True,
    )
    print(result.stdout)
    if result.returncode == 0:
        print_success(f"{script_name} passed.")
        return True
    print_fail(f"{script_name} failed.")
    if result.stderr:
        print(result.stderr)
    return False


def check_zeroLose_build() -> bool:
    """Type-check / build the ZeroLose macOS app if Xcode is available.

    This is the only real code gate in the suite: without it, verify_all can
    pass while the Swift project is broken. Using a generic destination keeps
    the build hardware-independent and avoids requiring a configured simulator.
    """
    project = ROOT / "ZeroLose" / "ZeroLose.xcodeproj"
    if not project.exists():
        print_warning("ZeroLose.xcodeproj not found; skipping build check.")
        return True

    try:
        subprocess.run(["xcodebuild", "-version"], capture_output=True, check=True)
    except (FileNotFoundError, subprocess.CalledProcessError):
        print_warning("xcodebuild not available; skipping ZeroLose build check.")
        return True

    print_info("Running ZeroLose build (generic macOS, no signing)...")
    result = subprocess.run(
        [
            "xcodebuild",
            "-project", str(project),
            "-scheme", "ZeroLose",
            "-configuration", "Debug",
            "-destination", "generic/platform=macOS",
            "-derivedDataPath", str(ROOT / "ZeroLose" / "build" / "DD"),
            "CODE_SIGNING_ALLOWED=NO",
            "build",
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        print_success("ZeroLose build passed.")
        return True
    print_fail("ZeroLose build failed.")
    # Print the relevant stderr tail but avoid dumping hundreds of linker lines.
    lines = result.stderr.splitlines() or result.stdout.splitlines()
    for line in lines[-30:]:
        if any(k in line.lower() for k in ("error:", "failed", "warning:")):
            print(line if len(line) < 300 else line[:300])
    return False


def write_scan_results(ok: bool) -> None:
    """Write a truthful, regenerated scan_results.json instead of leaving stale claims."""
    scan = {
        "project": str(ROOT.relative_to(ROOT.parent)) if ROOT.parent else ".",
        "timestamp": datetime.now().isoformat(),
        "scan_type": "maestro_verify_all",
        "scans": {
            "provider_config": {
                "tool": "provider_config_validator.py",
                "status": "[OK]" if ok else "[FAIL]",
                "findings": [],
            },
            "structure": {
                "tool": "checklist.py",
                "status": "[OK]" if ok else "[FAIL]",
                "findings": [],
            },
            "dependencies": {
                "tool": "dependency_analyzer.py",
                "status": "[OK]" if ok else "[FAIL]",
                "findings": [],
            },
        },
        "notes": "Regenerated by scripts/verify_all.py. Do not edit manually.",
    }
    (ROOT / "scan_results.json").write_text(
        json.dumps(scan, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    print_header("MAESTRO FULL VERIFICATION SUITE")

    scripts_to_run = [
        "sync_agents.py",
        "provider_config_validator.py",
        "checklist.py",
        "dependency_analyzer.py",
    ]

    all_success = True
    for script in scripts_to_run:
        if not run_script(script):
            all_success = False

    # Real code gate: build the Swift app so verify_all cannot pass while the
    # project is broken.
    if not check_zeroLose_build():
        all_success = False

    # A failed verification should still record the failure, not silently keep
    # the previous "all OK" result.
    write_scan_results(all_success)

    if all_success:
        print_header("FINAL VERIFICATION: SUCCESS")
        return 0
    print_header("FINAL VERIFICATION: FAILED")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
